enum SortStatus {
  OFF,
  NAME_INCREASING,
  NAME_DECREASING,
  SUM_INCREASING,
  SUM_DECREASING,
  CREATE_DATE_INCREASING,
  CREATE_DATE_DECREASING,
  FINISH_DATE_INCREASING,
  FINISH_DATE_DECREASING,
  SHOW_FINISHED,
}