name: goal_bank
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.1+10
  provider: ^3.1.0+1
  shared_preferences: ^0.5.4+3
  intl: ^0.16.0
  firebase_messaging: ^5.1.6
  firebase_auth: ^0.14.0+5
  firebase_admob: ^0.9.0+7
  flutter_svg: ^0.15.0
  carousel_slider: ^1.3.1
  get_it: ^2.0.3
  http: ^0.12.0+2
  confetti: ^0.3.0
  animated_splash: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.4"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"
  adaptive_icon_background: "#3084FF"
  adaptive_icon_foreground: "assets/launcher_icon.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/sort-by-attributes-interface-button-option.svg
    - assets/svg/house.svg
    - assets/svg/date.svg
    - assets/svg/info.svg
    - assets/svg/settings.svg
    - assets/on1.png
    - assets/on2.png
    - assets/on3.png
    - assets/bmw_image.jpg
    - assets/icon.png
    - assets/svg/congrads.svg
    - assets/svg/cta.svg
    - assets/svg/appvesto_logo.svg
    - assets/appvesto_logo.png
    - assets/black_appvesto_logo.png
    - assets/launcher_icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SvgIcons
      fonts:
        - asset: assets/fonts/SvgIcons.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/Ubuntu/Ubuntu-Regular.ttf
        - asset: assets/Ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat/Montserrat-Regular.ttf
        - asset: assets/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/Montserrat/Montserrat-Bold.ttf
          weight: 700


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
