/// Flutter icons SvgIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SvgIcons
///      fonts:
///       - asset: fonts/SvgIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SvgIcons {
  SvgIcons._();

  static const _kFontFam = 'SvgIcons';

  static const IconData info = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData onboardings = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData house = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData settings_tapbar = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData delete = const IconData(0xe804, fontFamily: _kFontFam);
}
